#!/usr/bin/env python3
"""Build the self-contained parts of scribb's skills for claude.ai chat.

In chat, only a skill's own folder reaches the sandbox, so the skills that
work there (write, review, scribb-style, learn) each carry:
  references/   the packs' guides, summaries, samples, formats and role maps
  scripts/      check.py (the checker without Vale) and rules.json

These files are generated from plugin/packs/. Edit the packs, then run:
  python3 tools/build-chat.py           # regenerate
  python3 tools/build-chat.py --check   # fail if anything is out of date (CI)
"""

import filecmp
import json
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACKS = os.path.join(ROOT, "plugin", "packs")
SKILLS = os.path.join(ROOT, "plugin", "skills")
CHAT_SKILLS = ["write", "review", "scribb-style", "learn", "style"]
CHECKER = os.path.join(ROOT, "tools", "chat", "check.py")
HEADER = "Generated by tools/build-chat.py from plugin/packs/. Don't edit; edit the packs and rebuild.\n"


# --- A small YAML subset: the forms scribb's pack.yaml and rule files use ---

def scalar(v):
    v = v.strip()
    if v.startswith("'") and v.endswith("'") and len(v) >= 2:
        return v[1:-1].replace("''", "'")
    if v.startswith('"') and v.endswith('"') and len(v) >= 2:
        return json.loads(v)
    if v in ("true", "false"):
        return v == "true"
    if v in ("null", "~", ""):
        return None
    if re.fullmatch(r"-?\d+", v):
        return int(v)
    if re.fullmatch(r"-?\d+\.\d+", v):
        return float(v)
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        return [scalar(x) for x in re.findall(r"""'(?:[^']|'')*'|"(?:[^"\\]|\\.)*"|[^,]+""", inner)] if inner else []
    return v


def strip_comment(line):
    out, q = [], None
    for i, c in enumerate(line):
        if q:
            out.append(c)
            if c == q:
                q = None
        elif c in "'\"":
            q = c
            out.append(c)
        elif c == "#" and (i == 0 or line[i - 1] in " \t"):
            break
        else:
            out.append(c)
    return "".join(out).rstrip()


def parse_yaml(text):
    data, key, container = {}, None, None
    for raw in text.splitlines():
        line = strip_comment(raw)
        if not line.strip():
            continue
        if not line.startswith((" ", "\t", "-")):
            m = re.match(r"([A-Za-z_][\w-]*):\s*(.*)$", line)
            if not m:
                raise ValueError(f"can't parse line: {raw!r}")
            key, rest = m.group(1), m.group(2)
            if rest == "":
                data[key], container = None, key
            else:
                data[key], container = scalar(rest), None
            continue
        item = line.strip()
        if container is None:
            continue  # nested structure we don't need (for example sources:)
        if item.startswith("- "):
            if data[container] is None:
                data[container] = []
            if isinstance(data[container], list):
                data[container].append(scalar(item[2:]))
        else:
            # A key ends at the first colon followed by a space; a regex key
            # such as "utiliz(?:e|es)" has colons with no space after them.
            m = re.match(r"""((?:'(?:[^']|'')*')|(?:"(?:[^"\\]|\\.)*")|.+?):\s+(.*)$""", item)
            if m:
                if data[container] is None:
                    data[container] = {}
                if isinstance(data[container], dict):
                    data[container][str(scalar(m.group(1)))] = scalar(m.group(2))
    return data


# --- Build ---------------------------------------------------------------------

def pack_dirs():
    yield os.path.join(PACKS, "base")
    for kind in ("content-types", "styles"):
        d = os.path.join(PACKS, kind)
        for name in sorted(os.listdir(d)):
            if os.path.isfile(os.path.join(d, name, "pack.yaml")):
                yield os.path.join(d, name)


def compile_rules():
    out = {}
    for d in pack_dirs():
        meta = parse_yaml(open(os.path.join(d, "pack.yaml"), encoding="utf-8").read())
        rules = []
        vale = os.path.join(d, "checks", "vale")
        if os.path.isdir(vale):
            for style in sorted(os.listdir(vale)):
                sdir = os.path.join(vale, style)
                if style in ("tests", "config") or not os.path.isdir(sdir):
                    continue
                for f in sorted(os.listdir(sdir)):
                    if f.endswith(".yml"):
                        r = parse_yaml(open(os.path.join(sdir, f), encoding="utf-8").read())
                        r["id"] = f"{style}.{f[:-4]}"
                        rules.append(r)
        out[meta["id"]] = {
            "kind": meta.get("kind"),
            "label": meta.get("label"),
            "tagline": meta.get("tagline"),
            "freedom": meta.get("freedom"),
            "version": meta.get("version"),
            "rules": rules,
        }
    return out


def copy_references(dest):
    for d in pack_dirs():
        rel = os.path.relpath(d, PACKS)
        target = os.path.join(dest, rel)
        os.makedirs(target, exist_ok=True)
        for name in ("pack.yaml", "summary.md", "guide.md", "sample.md"):
            src = os.path.join(d, name)
            if os.path.isfile(src):
                shutil.copy2(src, os.path.join(target, name))
        for sub in ("formats", "roles"):
            src = os.path.join(d, sub)
            if os.path.isdir(src):
                shutil.copytree(src, os.path.join(target, sub))


def build_into(skills_root):
    rules = json.dumps(compile_rules(), indent=1, ensure_ascii=False, sort_keys=True) + "\n"
    for skill in CHAT_SKILLS:
        sdir = os.path.join(skills_root, skill)
        for sub in ("references", "scripts"):
            shutil.rmtree(os.path.join(sdir, sub), ignore_errors=True)
        refs = os.path.join(sdir, "references")
        copy_references(refs)
        with open(os.path.join(refs, "GENERATED.txt"), "w", encoding="utf-8") as f:
            f.write(HEADER)
        scripts = os.path.join(sdir, "scripts")
        os.makedirs(scripts)
        shutil.copy2(CHECKER, os.path.join(scripts, "check.py"))
        with open(os.path.join(scripts, "rules.json"), "w", encoding="utf-8") as f:
            f.write(rules)


def same_tree(a, b):
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.diff_files or cmp.funny_files:
        return False
    for sub in cmp.common_dirs:
        if not same_tree(os.path.join(a, sub), os.path.join(b, sub)):
            return False
    # dircmp compares shallowly; confirm contents
    for f in cmp.common_files:
        if not filecmp.cmp(os.path.join(a, f), os.path.join(b, f), shallow=False):
            return False
    return True


def main():
    if "--check" in sys.argv:
        tmp = tempfile.mkdtemp()
        try:
            for skill in CHAT_SKILLS:
                os.makedirs(os.path.join(tmp, skill))
            build_into(tmp)
            stale = [s for s in CHAT_SKILLS for sub in ("references", "scripts")
                     if not os.path.isdir(os.path.join(SKILLS, s, sub))
                     or not same_tree(os.path.join(tmp, s, sub), os.path.join(SKILLS, s, sub))]
        finally:
            shutil.rmtree(tmp)
        if stale:
            print("build-chat: generated files are out of date. Run: python3 tools/build-chat.py")
            return 1
        print("build-chat: generated files are up to date.")
        return 0
    build_into(SKILLS)
    n = len(compile_rules())
    print(f"build-chat: bundled {n} packs into {', '.join(CHAT_SKILLS)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
