#!/usr/bin/env python3
"""Build the self-contained parts of scribb's skills for claude.ai chat.

In chat, only a skill's own folder reaches the sandbox, so the skills that
work there (write, review, scribb-style, learn) each carry:
  references/   the packs' guides, summaries, samples, formats and role maps
  scripts/      check.py (the checker without Vale) and rules.json

These files are generated from plugin/packs/. Edit the packs, then run:
  python3 tools/build-chat.py           # regenerate
  python3 tools/build-chat.py --check   # fail if anything is out of date (CI)
"""

import filecmp
import json
import os
import re
import shutil
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACKS = os.path.join(ROOT, "plugin", "packs")
SKILLS = os.path.join(ROOT, "plugin", "skills")
CHAT_SKILLS = ["write", "review", "scribb-style", "learn", "style"]
CHECKER = os.path.join(ROOT, "tools", "chat", "check.py")
HEADER = "Generated by tools/build-chat.py from plugin/packs/. Don't edit; edit the packs and rebuild.\n"


# The YAML subset parser lives in tools/chat/check.py, which also needs it at
# runtime to load rules promoted from memories.
sys.path.insert(0, os.path.join(ROOT, "tools", "chat"))
from check import parse_yaml  # noqa: E402


# --- Build ---------------------------------------------------------------------

def pack_dirs():
    yield os.path.join(PACKS, "base")
    for kind in ("content-types", "styles"):
        d = os.path.join(PACKS, kind)
        for name in sorted(os.listdir(d)):
            if os.path.isfile(os.path.join(d, name, "pack.yaml")):
                yield os.path.join(d, name)


def compile_rules():
    out = {}
    for d in pack_dirs():
        meta = parse_yaml(open(os.path.join(d, "pack.yaml"), encoding="utf-8").read())
        rules = []
        vale = os.path.join(d, "checks", "vale")
        if os.path.isdir(vale):
            for style in sorted(os.listdir(vale)):
                sdir = os.path.join(vale, style)
                if style in ("tests", "config") or not os.path.isdir(sdir):
                    continue
                for f in sorted(os.listdir(sdir)):
                    if f.endswith(".yml"):
                        r = parse_yaml(open(os.path.join(sdir, f), encoding="utf-8").read())
                        r["id"] = f"{style}.{f[:-4]}"
                        rules.append(r)
        out[meta["id"]] = {
            "kind": meta.get("kind"),
            "label": meta.get("label"),
            "tagline": meta.get("tagline"),
            "freedom": meta.get("freedom"),
            "version": meta.get("version"),
            "rules": rules,
        }
    return out


def copy_references(dest):
    for d in pack_dirs():
        rel = os.path.relpath(d, PACKS)
        target = os.path.join(dest, rel)
        os.makedirs(target, exist_ok=True)
        for name in ("pack.yaml", "summary.md", "guide.md", "sample.md"):
            src = os.path.join(d, name)
            if os.path.isfile(src):
                shutil.copy2(src, os.path.join(target, name))
        for sub in ("formats", "roles"):
            src = os.path.join(d, sub)
            if os.path.isdir(src):
                shutil.copytree(src, os.path.join(target, sub))


def build_into(skills_root):
    rules = json.dumps(compile_rules(), indent=1, ensure_ascii=False, sort_keys=True) + "\n"
    for skill in CHAT_SKILLS:
        sdir = os.path.join(skills_root, skill)
        for sub in ("references", "scripts"):
            shutil.rmtree(os.path.join(sdir, sub), ignore_errors=True)
        refs = os.path.join(sdir, "references")
        copy_references(refs)
        with open(os.path.join(refs, "GENERATED.txt"), "w", encoding="utf-8") as f:
            f.write(HEADER)
        scripts = os.path.join(sdir, "scripts")
        os.makedirs(scripts)
        shutil.copy2(CHECKER, os.path.join(scripts, "check.py"))
        with open(os.path.join(scripts, "rules.json"), "w", encoding="utf-8") as f:
            f.write(rules)


def same_tree(a, b):
    cmp = filecmp.dircmp(a, b)
    if cmp.left_only or cmp.right_only or cmp.diff_files or cmp.funny_files:
        return False
    for sub in cmp.common_dirs:
        if not same_tree(os.path.join(a, sub), os.path.join(b, sub)):
            return False
    # dircmp compares shallowly; confirm contents
    for f in cmp.common_files:
        if not filecmp.cmp(os.path.join(a, f), os.path.join(b, f), shallow=False):
            return False
    return True


def main():
    if "--check" in sys.argv:
        tmp = tempfile.mkdtemp()
        try:
            for skill in CHAT_SKILLS:
                os.makedirs(os.path.join(tmp, skill))
            build_into(tmp)
            stale = [s for s in CHAT_SKILLS for sub in ("references", "scripts")
                     if not os.path.isdir(os.path.join(SKILLS, s, sub))
                     or not same_tree(os.path.join(tmp, s, sub), os.path.join(SKILLS, s, sub))]
        finally:
            shutil.rmtree(tmp)
        if stale:
            print("build-chat: generated files are out of date. Run: python3 tools/build-chat.py")
            return 1
        print("build-chat: generated files are up to date.")
        return 0
    build_into(SKILLS)
    n = len(compile_rules())
    print(f"build-chat: bundled {n} packs into {', '.join(CHAT_SKILLS)}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
